modelo:
  version: api/v1
  metadata:
    name: null
    author: Ed Scrimaglia
    email: edscrimaglia@octupus.com
    tags: null
  specifications:
    environment:
      repository: null
      ssh_config_file: null
      debug: false
      ansible_command_timeout: 180
      module_command_timeout: 1800
      sleep_time: 0
    resources:
      devices:
        - nombre: null
          familia: null
          memoria: 2024
          ip_address: 192.168.1.1
          interfaces:
            - number: 0
              tipo: gigabit
              slot: 1
              port: 1
            - number: 1
              tipo: gigabit
              slot: 1
              port: 1
      others:
        - other: null
